"""links on projects

Revision ID: 21ee2052357b
Revises: 8de7721eec9d
Create Date: 2019-09-20 17:55:58.443524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ee2052357b'
down_revision = '8de7721eec9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('desc', sa.String(length=2000), nullable=True),
    sa.Column('github', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('thumbnail', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=True)
    op.create_table('techs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('icon', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_techs_icon'), 'techs', ['icon'], unique=True)
    op.create_index(op.f('ix_techs_name'), 'techs', ['name'], unique=True)
    op.create_table('project_techs',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('tech_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tech_id'], ['techs.id'], )
    )
    op.drop_table('association')
    op.drop_index('ix_project_title', table_name='project')
    op.drop_table('project')
    op.drop_index('ix_tech_icon', table_name='tech')
    op.drop_index('ix_tech_name', table_name='tech')
    op.drop_table('tech')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tech',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tech_name', 'tech', ['name'], unique=1)
    op.create_index('ix_tech_icon', 'tech', ['icon'], unique=1)
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('desc', sa.VARCHAR(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_title', 'project', ['title'], unique=1)
    op.create_table('association',
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('tech_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['tech_id'], ['tech.id'], )
    )
    op.drop_table('project_techs')
    op.drop_index(op.f('ix_techs_name'), table_name='techs')
    op.drop_index(op.f('ix_techs_icon'), table_name='techs')
    op.drop_table('techs')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
