"""empty message

Revision ID: 8de7721eec9d
Revises: 464ae39bedd6
Create Date: 2019-09-20 16:53:33.282385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8de7721eec9d'
down_revision = '464ae39bedd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('github', sa.String(length=200), nullable=True))
    op.add_column('project', sa.Column('thumbnail', sa.String(length=500), nullable=True))
    op.add_column('project', sa.Column('url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'url')
    op.drop_column('project', 'thumbnail')
    op.drop_column('project', 'github')
    # ### end Alembic commands ###
